site_name: Majmun
site_url: https://mazzz1y.github.io/majmun
repo_url: https://github.com/mazzz1y/majmun
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.instant
    - toc.follow

markdown_extensions:
  - toc:
      anchorlink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Install: install.md
  - Configuration:
      - Overview: config.md
      - Logs: config/logs.md
      - HTTP Client: config/http_client.md
      - Server: config/server.md
      - URL Generator: config/url_generator.md
      - Proxy: config/proxy.md
      - Playlists: config/playlists.md
      - EPGs: config/epgs.md
      - Clients: config/clients.md
      - Rules:
          - Overview: config/rules/index.md
          - Channel Rules:
              - Set Field: config/rules/channel_rules/set_field.md
              - Remove Field: config/rules/channel_rules/remove_field.md
              - Remove Channel: config/rules/channel_rules/remove_channel.md
              - Mark Hidden: config/rules/channel_rules/mark_hidden.md
          - Playlist Rules:
              - Remove Duplicates: config/rules/playlist_rules/remove_duplicates.md
              - Merge Duplicates: config/rules/playlist_rules/merge_duplicates.md
              - Sort: config/rules/playlist_rules/sort.md
          - Shared Objects:
              - Condition: config/rules/condition.md
              - Selector: config/rules/selector.md
              - Final Value: config/rules/final_value.md
  - Examples: examples.md
  - Metrics: metrics.md
